DELETE http://localhost:3003/api/blogs/6414af1e3d5e4f4bf9ac40ec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhdW5vIiwiaWQiOiI2NDE0YTBjNzgzNDA3MjM2M2ExOGU5YmYiLCJpYXQiOjE2NzkwNzg2NDF9.TLGnjrBl59Zlw0afIOawY67YTm908pO2XRnnRbHJYm0