POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJhdW5vIiwiaWQiOiI2NDE1YTMwNDgzOTAyYWZmMmI4YzE0ZjgiLCJpYXQiOjE2NzkxMzk2NDQsImV4cCI6MTY3OTE0MzI0NH0.IVhDlabjzblIX6kQINnYhvuhmccELlSeKm5CrTA4HzU

{
    "title": "Uutiset talouspolitiikasta",
    "author": "Rauno",
    "url": "randomurl/morovaaaaa.com/uutiset",
    "likes": 11
}